import type { ApiEndpoint } from "@/features/developers/lib/api-reference-data";

// API.md § 6-8 (Folders + Convites/membros de Folder + Sections).
export function buildFolderEndpoints(workspaceId: string): ApiEndpoint[] {
  return [
    {
      method: "POST",
      path: `/workspaces/${workspaceId}/folders`,
      summary: "Criar uma pasta",
      description: "`parentId` opcional cria como subpasta — pastas formam uma árvore de profundidade arbitrária dentro do workspace.",
      bodyParams: [
        { name: "name", type: "string", required: true },
        { name: "description", type: "string", required: false },
        { name: "parentId", type: "string", required: false },
      ],
      requestExample: [
        `curl -X POST "$API_URL/workspaces/${workspaceId}/folders" \\`,
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        '  -H "Content-Type: application/json" \\',
        "  -d '{ \"name\": \"Website Redesign\" }'",
      ].join("\n"),
      responseStatus: "201 Created",
      responseExample: [
        "{",
        `  "id": "uuid", "workspaceId": "${workspaceId}", "parentId": null, "name": "Website Redesign",`,
        '  "description": null, "status": "ACTIVE", "createdBy": "uuid", "version": 1, "createdAt": "...", "updatedAt": "..."',
        "}",
      ].join("\n"),
    },
    {
      method: "GET",
      path: `/workspaces/${workspaceId}/folders`,
      summary: "Listar pastas do workspace",
      description: "Paginado, cacheado. Retorna todas as pastas (planas, cada uma com `parentId`) — monte a árvore no cliente.",
      requestExample: [
        `curl "$API_URL/workspaces/${workspaceId}/folders" \\`,
        '  -H "Authorization: Bearer $ACCESS_TOKEN"',
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "data": [ { "id": "...", "parentId": null, "...": "..." } ], "meta": { "...": "..." } }',
    },
    {
      method: "GET",
      path: "/folders/:folderId",
      summary: "Detalhe de uma pasta",
      description: "Cacheado.",
      requestExample: ['curl "$API_URL/folders/FOLDER_ID" \\', '  -H "Authorization: Bearer $ACCESS_TOKEN"'].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "id": "FOLDER_ID", "name": "Website Redesign", "status": "ACTIVE", "...": "..." }',
      errorCodes: ["FOLDER_NOT_FOUND", "FORBIDDEN_WORKSPACE_ACTION"],
    },
    {
      method: "PATCH",
      path: "/folders/:folderId",
      summary: "Editar nome/descrição",
      bodyParams: [
        { name: "name", type: "string", required: false },
        { name: "description", type: "string", required: false },
      ],
      requestExample: [
        'curl -X PATCH "$API_URL/folders/FOLDER_ID" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        '  -H "Content-Type: application/json" \\',
        "  -d '{ \"description\": \"Novo escopo\" }'",
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "id": "FOLDER_ID", "description": "Novo escopo", "...": "..." }',
    },
    {
      method: "PATCH",
      path: "/folders/:folderId/archive",
      summary: "Arquivar",
      description: "Não há \"desarquivar\" nem delete explícito. Bloqueado se a pasta tiver subpastas ainda ativas.",
      requestExample: [
        'curl -X PATCH "$API_URL/folders/FOLDER_ID/archive" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN"',
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "id": "FOLDER_ID", "status": "ARCHIVED", "...": "..." }',
      errorCodes: ["FOLDER_HAS_CHILDREN"],
    },
    {
      method: "GET",
      path: "/folders/:folderId/subfolders",
      summary: "Subpastas diretas",
      description: "Paginado, cacheado. Um nível só, mais antigos primeiro.",
      requestExample: [
        'curl "$API_URL/folders/FOLDER_ID/subfolders" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN"',
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "data": [ { "id": "...", "parentId": "FOLDER_ID", "...": "..." } ], "meta": { "...": "..." } }',
      errorCodes: ["FOLDER_NOT_FOUND", "FORBIDDEN_WORKSPACE_ACTION"],
    },
    {
      method: "PATCH",
      path: "/folders/:folderId/move",
      summary: "Mover na árvore de pastas",
      bodyParams: [{ name: "parentId", type: "string | null", required: true, notes: "null promove a pasta raiz" }],
      requestExample: [
        'curl -X PATCH "$API_URL/folders/FOLDER_ID/move" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        '  -H "Content-Type: application/json" \\',
        "  -d '{ \"parentId\": null }'",
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "id": "FOLDER_ID", "parentId": null, "...": "..." }',
      notes: [
        "Membership em cascata: quem tem acesso via `FolderMember` a uma pasta ganha acesso a todas as descendentes dela — mover uma pasta muda quem tem acesso a ela.",
      ],
      errorCodes: ["CANNOT_BE_OWN_PARENT", "CANNOT_MOVE_INTO_OWN_DESCENDANT", "PARENT_OUT_OF_SCOPE", "PARENT_FOLDER_ARCHIVED", "FOLDER_NOT_FOUND", "FORBIDDEN_WORKSPACE_ACTION"],
    },
    {
      method: "POST",
      path: "/folders/:folderId/invitations",
      summary: "Convidar para a pasta",
      description: "Análogo ao convite de workspace, mas escopado a esta pasta (acesso pontual sem entrar no workspace inteiro).",
      bodyParams: [
        { name: "email", type: "string", required: true },
        { name: "role", type: '"MEMBER" | "GUEST"', required: true },
      ],
      requestExample: [
        'curl -X POST "$API_URL/folders/FOLDER_ID/invitations" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        '  -H "Content-Type: application/json" \\',
        "  -d '{ \"email\": \"colaborador@example.com\", \"role\": \"MEMBER\" }'",
      ].join("\n"),
      responseStatus: "201 Created",
      responseExample: '{ "id": "uuid", "folderId": "FOLDER_ID", "email": "colaborador@example.com", "status": "PENDING", "...": "..." }',
    },
    {
      method: "GET",
      path: "/folders/:folderId/invitations",
      summary: "Listar convites da pasta",
      description: "Paginado, cacheado.",
      requestExample: [
        'curl "$API_URL/folders/FOLDER_ID/invitations" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN"',
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "data": [ "..." ], "meta": { "...": "..." } }',
    },
    {
      method: "DELETE",
      path: "/folders/:folderId/invitations/:invitationId",
      summary: "Revogar convite da pasta",
      requestExample: [
        'curl -X DELETE "$API_URL/folders/FOLDER_ID/invitations/INVITATION_ID" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN"',
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "revoked": true }',
      errorCodes: ["INVITATION_NOT_FOUND", "INVITATION_ALREADY_PROCESSED"],
    },
    {
      method: "GET",
      path: "/folders/invitations/:token/preview",
      summary: "Pré-visualizar convite de pasta (público)",
      description: "Igual ao preview de workspace, com `folderId`/`folderName`. Cacheado por 30s.",
      requestExample: ['curl "$API_URL/folders/invitations/TOKEN/preview"'].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "folderId": "FOLDER_ID", "folderName": "Website Redesign", "email": "...", "role": "MEMBER", "status": "PENDING", "expiresAt": "..." }',
      errorCodes: ["INVITATION_NOT_FOUND"],
    },
    {
      method: "POST",
      path: "/folders/invitations/:token/accept",
      summary: "Aceitar convite de pasta",
      requestExample: [
        'curl -X POST "$API_URL/folders/invitations/TOKEN/accept" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN"',
      ].join("\n"),
      responseStatus: "201 Created",
      responseExample: '{ "folderId": "FOLDER_ID", "userId": "uuid", "role": "MEMBER" }',
      errorCodes: ["INVITATION_NOT_FOUND", "INVITATION_EXPIRED", "INVITATION_ALREADY_PROCESSED", "INVITATION_EMAIL_MISMATCH"],
    },
    {
      method: "GET",
      path: "/folders/:folderId/members",
      summary: "Listar membros da pasta",
      description:
        "Paginado, cacheado. Só lista membros diretos (`FolderMember`) — quem tem acesso só por herança de uma pasta ancestral não aparece aqui.",
      requestExample: [
        'curl "$API_URL/folders/FOLDER_ID/members" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN"',
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "data": [ { "userId": "uuid", "name": "Jane Doe", "role": "MEMBER", "createdAt": "..." } ], "meta": { "...": "..." } }',
    },
    {
      method: "DELETE",
      path: "/folders/:folderId/members/:userId",
      summary: "Remover acesso de um membro",
      description: "Só remove membership direta — para tirar acesso herdado, remova o membro na pasta ancestral onde foi adicionado.",
      requestExample: [
        'curl -X DELETE "$API_URL/folders/FOLDER_ID/members/USER_ID" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN"',
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "removed": true }',
      errorCodes: ["MEMBER_NOT_FOUND"],
    },
    {
      method: "POST",
      path: "/folders/:folderId/sections",
      summary: "Criar uma section",
      description:
        "Sempre entra ao final da lista de irmãs (mesmo `parentId`) — nunca `isDefault`, essa nasce sozinha com a pasta. `parentId` opcional cria como sub-seção.",
      bodyParams: [
        { name: "name", type: "string", required: true },
        { name: "parentId", type: "string", required: false },
      ],
      requestExample: [
        'curl -X POST "$API_URL/folders/FOLDER_ID/sections" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        '  -H "Content-Type: application/json" \\',
        "  -d '{ \"name\": \"In Progress\" }'",
      ].join("\n"),
      responseStatus: "201 Created",
      responseExample: [
        "{",
        '  "id": "uuid", "folderId": "FOLDER_ID", "parentId": null, "name": "In Progress",',
        '  "position": 1, "isDefault": false, "version": 1, "createdAt": "...", "updatedAt": "..."',
        "}",
      ].join("\n"),
      errorCodes: ["FOLDER_NOT_FOUND", "SECTION_NOT_FOUND", "PARENT_OUT_OF_SCOPE"],
    },
    {
      method: "GET",
      path: "/folders/:folderId/sections",
      summary: "Listar sections da pasta",
      description: "Paginado, cacheado. Todas as sections (todos os níveis), ordenadas por `position` — monte a árvore agrupando por `parentId`.",
      requestExample: [
        'curl "$API_URL/folders/FOLDER_ID/sections" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN"',
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "data": [ { "id": "...", "position": 0, "...": "..." } ], "meta": { "...": "..." } }',
    },
    {
      method: "PATCH",
      path: "/sections/:sectionId",
      summary: "Renomear/reordenar",
      description: "`position` (0-based) reordena entre as irmãs atuais — sempre clampada, nunca lança erro por estar fora do intervalo.",
      bodyParams: [
        { name: "name", type: "string", required: false },
        { name: "position", type: "number", required: false },
      ],
      requestExample: [
        'curl -X PATCH "$API_URL/sections/SECTION_ID" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        '  -H "Content-Type: application/json" \\',
        "  -d '{ \"position\": 0 }'",
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "id": "SECTION_ID", "position": 0, "...": "..." }',
      errorCodes: ["SECTION_NOT_FOUND"],
    },
    {
      method: "PATCH",
      path: "/sections/:sectionId/move",
      summary: "Mover para outro pai",
      bodyParams: [
        { name: "parentId", type: "string | null", required: true },
        { name: "position", type: "number", required: false, notes: "omitido entra ao final" },
      ],
      requestExample: [
        'curl -X PATCH "$API_URL/sections/SECTION_ID/move" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        '  -H "Content-Type: application/json" \\',
        "  -d '{ \"parentId\": null }'",
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "id": "SECTION_ID", "parentId": null, "...": "..." }',
      errorCodes: ["CANNOT_BE_OWN_PARENT", "CANNOT_MOVE_INTO_OWN_DESCENDANT", "PARENT_OUT_OF_SCOPE", "SECTION_NOT_FOUND", "FORBIDDEN_WORKSPACE_ACTION"],
    },
    {
      method: "DELETE",
      path: "/sections/:sectionId",
      summary: "Apagar",
      description: "Bloqueado se for a section padrão, se tiver sub-seções, ou se ainda tiver items.",
      requestExample: [
        'curl -X DELETE "$API_URL/sections/SECTION_ID" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN"',
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "deleted": true, "folderId": "FOLDER_ID" }',
      errorCodes: ["DEFAULT_SECTION_NOT_DELETABLE", "SECTION_HAS_CHILDREN", "SECTION_NOT_EMPTY"],
    },
  ];
}
