import type { ApiEndpoint } from "@/features/developers/lib/api-reference-data";

const ITEM_DTO_STUB =
  '{ "id": "ITEM_ID", "folderId": "FOLDER_ID", "sectionId": "SECTION_ID", "position": 0, "parentItemId": null, "title": "Fix login bug", "description": null, "status": "TODO", "assigneeId": null, "dueDate": null, "priority": null, "createdBy": "uuid", "version": 1, "hasCover": false, "coverUrl": null, "attachments": [], "participantIds": [], "mentionedUserIds": [], "...": "..." }';

// API.md § 9 (Items) — o maior grupo de rotas da API, tudo escopado a
// pasta/item, sem depender do workspaceId da página. Custom fields e
// comments (§ 10-11) ficam em `buildCustomFieldEndpoints`/`buildCommentEndpoints`
// abaixo, para a UI apresentá-los como sub-seções separadas.
export function buildItemEndpoints(): ApiEndpoint[] {
  return [
    {
      method: "POST",
      path: "/folders/:folderId/items",
      summary: "Criar um item",
      description:
        "`sectionId` omitido usa a section padrão da pasta. `position` é sempre atribuída ao final da lista — para escolher a posição, crie e reordene em seguida via `PATCH`.",
      bodyParams: [
        { name: "title", type: "string", required: true },
        { name: "sectionId", type: "string", required: false, notes: "padrão: section padrão da pasta" },
        { name: "description", type: "string", required: false },
        { name: "assigneeId", type: "string", required: false },
        { name: "parentItemId", type: "string", required: false, notes: "cria como subitem" },
        { name: "dueDate", type: "string (ISO 8601)", required: false },
        { name: "priority", type: '"LOW" | "MEDIUM" | "HIGH" | "URGENT"', required: false },
        { name: "mentionedUserIds", type: "string[]", required: false, notes: "até 50 uuids" },
      ],
      requestExample: [
        'curl -X POST "$API_URL/folders/FOLDER_ID/items" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        '  -H "Content-Type: application/json" \\',
        "  -d '{ \"title\": \"Fix login bug\" }'",
      ].join("\n"),
      responseStatus: "201 Created",
      responseExample: ITEM_DTO_STUB,
      errorCodes: ["SUBITEM_FOLDER_MISMATCH", "SECTION_NOT_FOUND", "SECTION_FOLDER_MISMATCH", "ASSIGNEE_NOT_FOLDER_MEMBER", "MENTIONED_USER_NOT_FOLDER_MEMBER"],
    },
    {
      method: "GET",
      path: "/folders/:folderId/items",
      summary: "Listar items de nível superior",
      description: "Paginado, cacheado. Tipicamente os items que não são subitem de nenhum outro.",
      requestExample: [
        'curl "$API_URL/folders/FOLDER_ID/items" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN"',
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: `{ "data": [ ${ITEM_DTO_STUB} ], "meta": { "...": "..." } }`,
    },
    {
      method: "GET",
      path: "/sections/:sectionId/items",
      summary: "Listar items de uma section",
      description: "Paginado, cacheado. Visão tipo Kanban — vem ordenado por `position` ascendente, renderize direto.",
      requestExample: [
        'curl "$API_URL/sections/SECTION_ID/items" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN"',
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: `{ "data": [ ${ITEM_DTO_STUB} ], "meta": { "...": "..." } }`,
      errorCodes: ["SECTION_NOT_FOUND"],
    },
    {
      method: "GET",
      path: "/items/:itemId",
      summary: "Detalhe de um item",
      description: "Cacheado.",
      requestExample: ['curl "$API_URL/items/ITEM_ID" \\', '  -H "Authorization: Bearer $ACCESS_TOKEN"'].join("\n"),
      responseStatus: "200 OK",
      responseExample: ITEM_DTO_STUB,
      errorCodes: ["ITEM_NOT_FOUND"],
    },
    {
      method: "GET",
      path: "/items/:itemId/subitems",
      summary: "Listar subitems diretas",
      description: "Paginado, cacheado.",
      requestExample: [
        'curl "$API_URL/items/ITEM_ID/subitems" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN"',
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: `{ "data": [ ${ITEM_DTO_STUB} ], "meta": { "...": "..." } }`,
    },
    {
      method: "PATCH",
      path: "/items/:itemId",
      summary: "Editar/mover/reparentar",
      description:
        "`sectionId`+`position` move e reordena numa chamada só; `parentItemId` reparenta (`null` promove o item de topo). `mentionedUserIds` substitui o conjunto atual de menções (`[]` remove todas, omitido não altera). Não é possível limpar `dueDate`/`priority`/`assigneeId` (`null`) por esta rota — só via sync.",
      bodyParams: [
        { name: "title", type: "string", required: false },
        { name: "description", type: "string", required: false },
        { name: "assigneeId", type: "string", required: false },
        { name: "sectionId", type: "string", required: false },
        { name: "position", type: "number", required: false, notes: "0-based, sempre clampada" },
        { name: "dueDate", type: "string (ISO 8601)", required: false },
        { name: "priority", type: '"LOW" | "MEDIUM" | "HIGH" | "URGENT"', required: false },
        { name: "parentItemId", type: "string | null", required: false },
        { name: "mentionedUserIds", type: "string[]", required: false },
      ],
      requestExample: [
        'curl -X PATCH "$API_URL/items/ITEM_ID" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        '  -H "Content-Type: application/json" \\',
        "  -d '{ \"sectionId\": \"SECTION_ID\", \"position\": 0 }'",
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: ITEM_DTO_STUB,
      errorCodes: ["SECTION_NOT_FOUND", "SECTION_FOLDER_MISMATCH", "MENTIONED_USER_NOT_FOLDER_MEMBER", "ASSIGNEE_NOT_FOLDER_MEMBER", "ITEM_NOT_FOUND", "SUBITEM_FOLDER_MISMATCH", "CANNOT_BE_OWN_PARENT", "CANNOT_MOVE_INTO_OWN_DESCENDANT"],
    },
    {
      method: "PATCH",
      path: "/items/:itemId/status",
      summary: "Mudar status",
      description: "Não é permitido concluir (`DONE`) um item com subitems pendentes.",
      bodyParams: [{ name: "status", type: '"TODO" | "IN_PROGRESS" | "DONE"', required: true }],
      requestExample: [
        'curl -X PATCH "$API_URL/items/ITEM_ID/status" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        '  -H "Content-Type: application/json" \\',
        "  -d '{ \"status\": \"IN_PROGRESS\" }'",
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: ITEM_DTO_STUB,
      errorCodes: ["ITEM_HAS_PENDING_SUBITEMS"],
    },
    {
      method: "POST",
      path: "/items/:itemId/attachments",
      summary: "Upload de anexo",
      description: "`multipart/form-data`, campo `file`. Limite de 20MB.",
      requestExample: [
        'curl -X POST "$API_URL/items/ITEM_ID/attachments" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        '  -F "file=@screenshot.png"',
      ].join("\n"),
      responseStatus: "201 Created",
      responseExample: ITEM_DTO_STUB,
    },
    {
      method: "GET",
      path: "/items/:itemId/attachments/:attachmentId/download",
      summary: "Baixar um anexo",
      description: "Binário com `Content-Disposition: attachment` — trate como download direto (fetch + blob, já que é rota protegida por JWT).",
      requestExample: [
        'curl "$API_URL/items/ITEM_ID/attachments/ATTACHMENT_ID/download" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        "  --output arquivo",
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: "(binário)",
      errorCodes: ["ITEM_NOT_FOUND", "ATTACHMENT_NOT_FOUND"],
    },
    {
      method: "DELETE",
      path: "/items/:itemId/attachments/:attachmentId",
      summary: "Remover um anexo",
      description: "Requer papel diferente de `GUEST` na pasta.",
      requestExample: [
        'curl -X DELETE "$API_URL/items/ITEM_ID/attachments/ATTACHMENT_ID" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN"',
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: ITEM_DTO_STUB,
      errorCodes: ["ITEM_NOT_FOUND", "ATTACHMENT_NOT_FOUND", "FORBIDDEN_WORKSPACE_ACTION"],
    },
    {
      method: "PUT",
      path: "/items/:itemId/cover",
      summary: "Definir/trocar a capa",
      description: "`multipart/form-data`, campo `file`. Limite de 10MB, JPEG/PNG/WebP pelo conteúdo. Trocar apaga a anterior do storage.",
      requestExample: [
        'curl -X PUT "$API_URL/items/ITEM_ID/cover" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        '  -F "file=@capa.jpg"',
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: ITEM_DTO_STUB,
      errorCodes: ["INVALID_ITEM_COVER", "ITEM_NOT_FOUND", "FORBIDDEN_WORKSPACE_ACTION"],
    },
    {
      method: "GET",
      path: "/items/:itemId/cover",
      summary: "Baixar a capa",
      description: "Qualquer papel com acesso à pasta pode ler (inclusive `GUEST`).",
      requestExample: [
        'curl "$API_URL/items/ITEM_ID/cover" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        "  --output capa.jpg",
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: "(binário)",
      errorCodes: ["ITEM_NOT_FOUND", "ITEM_COVER_NOT_FOUND", "FORBIDDEN_WORKSPACE_ACTION"],
    },
    {
      method: "DELETE",
      path: "/items/:itemId/cover",
      summary: "Remover a capa",
      description: "Idempotente — num item sem capa devolve o item como está.",
      requestExample: ['curl -X DELETE "$API_URL/items/ITEM_ID/cover" \\', '  -H "Authorization: Bearer $ACCESS_TOKEN"'].join(
        "\n",
      ),
      responseStatus: "200 OK",
      responseExample: ITEM_DTO_STUB,
      errorCodes: ["ITEM_NOT_FOUND", "FORBIDDEN_WORKSPACE_ACTION"],
    },
    {
      method: "POST",
      path: "/folders/:folderId/items/bulk",
      summary: "Criar items em lote",
      description: "Até 100 itens. Sucesso parcial sempre 200 — cada item processa exatamente como `POST /folders/:folderId/items`, na ordem enviada.",
      bodyParams: [{ name: "items", type: "CreateItemDto[]", required: true, notes: "máx. 100" }],
      requestExample: [
        'curl -X POST "$API_URL/folders/FOLDER_ID/items/bulk" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        '  -H "Content-Type: application/json" \\',
        "  -d '{ \"items\": [{ \"title\": \"Item 1\" }, { \"title\": \"Item 2\" }] }'",
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: [
        "{",
        '  "total": 2, "succeeded": 2, "failed": 0,',
        '  "results": [',
        '    { "index": 0, "itemId": "uuid", "status": "SUCCESS", "data": { "...": "ItemDto" } },',
        '    { "index": 1, "itemId": "uuid", "status": "SUCCESS", "data": { "...": "ItemDto" } }',
        "  ]",
        "}",
      ].join("\n"),
      notes: ["Um erro por item nunca desfaz os itens que já passaram (sem rollback)."],
      errorCodes: ["BULK_BATCH_TOO_LARGE"],
    },
    {
      method: "PATCH",
      path: "/items/bulk",
      summary: "Editar items em lote",
      description: "Até 100 itens, cada um um `PATCH /items/:itemId` completo. Não escopado a uma pasta — um lote pode misturar pastas.",
      bodyParams: [{ name: "items", type: "({ itemId } & UpdateItemDto)[]", required: true, notes: "máx. 100" }],
      requestExample: [
        'curl -X PATCH "$API_URL/items/bulk" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        '  -H "Content-Type: application/json" \\',
        "  -d '{ \"items\": [{ \"itemId\": \"uuid\", \"status\": \"DONE\" }] }'",
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "total": 1, "succeeded": 1, "failed": 0, "results": [ { "index": 0, "itemId": "uuid", "status": "SUCCESS", "data": { "...": "..." } } ] }',
      errorCodes: ["BULK_BATCH_TOO_LARGE"],
    },
    {
      method: "POST",
      path: "/items/bulk-delete",
      summary: "Remover items em lote",
      description: "Soft delete e leva junto todos os subitems (qualquer profundidade). Não existe `DELETE /items/:itemId` unitário — mande um id só aqui para isso.",
      bodyParams: [{ name: "itemIds", type: "string[]", required: true, notes: "sem repetição, máx. 100" }],
      requestExample: [
        'curl -X POST "$API_URL/items/bulk-delete" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        '  -H "Content-Type: application/json" \\',
        "  -d '{ \"itemIds\": [\"uuid\"] }'",
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "total": 1, "succeeded": 1, "failed": 0, "results": [ { "index": 0, "itemId": "uuid", "status": "SUCCESS", "data": { "id": "uuid", "folderId": "...", "deletedSubitemIds": [] } } ] }',
      errorCodes: ["BULK_BATCH_TOO_LARGE"],
    },
    {
      method: "POST",
      path: "/items/:itemId/participants",
      summary: "Adicionar participante",
      description: "Aditivo a `assigneeId`, sem hierarquia. Idempotente: adicionar quem já é participante é um no-op.",
      bodyParams: [{ name: "userId", type: "string", required: true }],
      requestExample: [
        'curl -X POST "$API_URL/items/ITEM_ID/participants" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        '  -H "Content-Type: application/json" \\',
        "  -d '{ \"userId\": \"uuid\" }'",
      ].join("\n"),
      responseStatus: "201 Created",
      responseExample: ITEM_DTO_STUB,
      errorCodes: ["ITEM_NOT_FOUND", "ASSIGNEE_NOT_FOLDER_MEMBER"],
    },
    {
      method: "DELETE",
      path: "/items/:itemId/participants/:userId",
      summary: "Remover participante",
      description: "Idempotente: remover quem já não é participante é um no-op.",
      requestExample: [
        'curl -X DELETE "$API_URL/items/ITEM_ID/participants/USER_ID" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN"',
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: ITEM_DTO_STUB,
      errorCodes: ["ITEM_NOT_FOUND"],
    },
  ];
}

// API.md § 10 (Custom Fields).
export function buildCustomFieldEndpoints(): ApiEndpoint[] {
  return [
    {
      method: "POST",
      path: "/folders/:folderId/custom-fields",
      summary: "Criar um campo personalizado",
      bodyParams: [
        { name: "name", type: "string", required: true },
        { name: "type", type: '"TEXT"|"NUMBER"|"DATE"|"SINGLE_SELECT"|"MULTI_SELECT"|"CHECKBOX"|"PEOPLE"', required: true },
        { name: "options", type: "string[]", required: false, notes: "obrigatório na prática para SINGLE_SELECT/MULTI_SELECT" },
      ],
      requestExample: [
        'curl -X POST "$API_URL/folders/FOLDER_ID/custom-fields" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        '  -H "Content-Type: application/json" \\',
        "  -d '{ \"name\": \"Priority\", \"type\": \"SINGLE_SELECT\", \"options\": [\"Low\",\"Medium\",\"High\"] }'",
      ].join("\n"),
      responseStatus: "201 Created",
      responseExample: '{ "id": "uuid", "folderId": "FOLDER_ID", "name": "Priority", "type": "SINGLE_SELECT", "options": ["Low","Medium","High"], "archived": false, "version": 1 }',
    },
    {
      method: "GET",
      path: "/folders/:folderId/custom-fields",
      summary: "Listar campos personalizados",
      description: "Paginado, cacheado.",
      requestExample: [
        'curl "$API_URL/folders/FOLDER_ID/custom-fields" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN"',
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "data": [ { "id": "...", "type": "SINGLE_SELECT", "...": "..." } ], "meta": { "...": "..." } }',
    },
    {
      method: "PATCH",
      path: "/custom-fields/:definitionId/options",
      summary: "Atualizar as opções",
      bodyParams: [{ name: "options", type: "string[]", required: true }],
      requestExample: [
        'curl -X PATCH "$API_URL/custom-fields/DEFINITION_ID/options" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        '  -H "Content-Type: application/json" \\',
        "  -d '{ \"options\": [\"Low\",\"Medium\",\"High\",\"Critical\"] }'",
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "id": "DEFINITION_ID", "options": ["Low","Medium","High","Critical"], "...": "..." }',
      errorCodes: ["CUSTOM_FIELD_NOT_FOUND"],
    },
    {
      method: "PATCH",
      path: "/custom-fields/:definitionId/archive",
      summary: "Arquivar",
      description: "Não pode mais ser usado/editado, mas valores existentes permanecem.",
      requestExample: [
        'curl -X PATCH "$API_URL/custom-fields/DEFINITION_ID/archive" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN"',
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "id": "DEFINITION_ID", "archived": true, "...": "..." }',
    },
    {
      method: "GET",
      path: "/items/:itemId/custom-field-values",
      summary: "Listar valores preenchidos num item",
      description: "Paginado, cacheado. `value` é polimórfico conforme o `type` da definição.",
      requestExample: [
        'curl "$API_URL/items/ITEM_ID/custom-field-values" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN"',
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "data": [ { "id": "uuid", "itemId": "ITEM_ID", "fieldDefinitionId": "uuid", "value": "High", "updatedAt": "..." } ], "meta": { "...": "..." } }',
    },
    {
      method: "PATCH",
      path: "/items/:itemId/custom-field-values/:definitionId",
      summary: "Definir/atualizar um valor",
      bodyParams: [{ name: "value", type: "string | number | boolean | string[]", required: true, notes: "conforme o type da definição" }],
      requestExample: [
        'curl -X PATCH "$API_URL/items/ITEM_ID/custom-field-values/DEFINITION_ID" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        '  -H "Content-Type: application/json" \\',
        "  -d '{ \"value\": \"High\" }'",
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "id": "uuid", "itemId": "ITEM_ID", "fieldDefinitionId": "DEFINITION_ID", "value": "High", "updatedAt": "..." }',
      errorCodes: ["CUSTOM_FIELD_VALUE_INVALID", "CUSTOM_FIELD_NOT_FOUND", "ITEM_NOT_FOUND"],
    },
  ];
}

// API.md § 11 (Comments).
export function buildCommentEndpoints(): ApiEndpoint[] {
  return [
    {
      method: "POST",
      path: "/items/:itemId/comments",
      summary: "Comentar (ou responder)",
      description: "`parentId` opcional responde a outro comentário (threading de profundidade arbitrária) — o pai precisa ser do mesmo item.",
      bodyParams: [
        { name: "content", type: "string", required: true, notes: "1 a 5000 caracteres" },
        { name: "parentId", type: "string", required: false },
        { name: "mentionedUserIds", type: "string[]", required: false, notes: "até 50 uuids" },
      ],
      requestExample: [
        'curl -X POST "$API_URL/items/ITEM_ID/comments" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        '  -H "Content-Type: application/json" \\',
        "  -d '{ \"content\": \"This looks good to me.\" }'",
      ].join("\n"),
      responseStatus: "201 Created",
      responseExample: '{ "id": "uuid", "itemId": "ITEM_ID", "parentId": null, "authorId": "uuid", "content": "This looks good to me.", "mentionedUserIds": [], "createdAt": "...", "updatedAt": "..." }',
      errorCodes: ["ITEM_NOT_FOUND", "MENTIONED_USER_NOT_FOLDER_MEMBER", "COMMENT_NOT_FOUND", "PARENT_OUT_OF_SCOPE", "COMMENT_CONTENT_INVALID", "FORBIDDEN_WORKSPACE_ACTION"],
    },
    {
      method: "GET",
      path: "/items/:itemId/comments",
      summary: "Listar comentários",
      description: "Paginado, cacheado, ordenado por `createdAt` ascendente. Lista plana com `parentId` — monte a thread no cliente.",
      requestExample: [
        'curl "$API_URL/items/ITEM_ID/comments" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN"',
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "data": [ { "id": "...", "parentId": null, "...": "..." } ], "meta": { "...": "..." } }',
      errorCodes: ["ITEM_NOT_FOUND", "FORBIDDEN_WORKSPACE_ACTION"],
    },
    {
      method: "DELETE",
      path: "/comments/:commentId",
      summary: "Apagar (hard delete)",
      description: "Sem edição nesta versão. Só o autor ou um `OWNER`/`ADMIN` do workspace pode apagar. Bloqueado se ainda tiver respostas.",
      requestExample: [
        'curl -X DELETE "$API_URL/comments/COMMENT_ID" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN"',
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "id": "COMMENT_ID", "itemId": "ITEM_ID" }',
      errorCodes: ["COMMENT_NOT_FOUND", "COMMENT_AUTHOR_MISMATCH", "COMMENT_HAS_CHILDREN"],
    },
  ];
}
