import type { ApiEndpoint } from "@/features/developers/lib/api-reference-data";

// API.md § 6-8 (Projects + Convites/membros de Project + Sections).
export function buildProjectEndpoints(workspaceId: string): ApiEndpoint[] {
  return [
    {
      method: "POST",
      path: `/workspaces/${workspaceId}/projects`,
      summary: "Criar um projeto",
      description: "`parentId` opcional cria como sub-projeto — projetos formam uma árvore de profundidade arbitrária dentro do workspace.",
      bodyParams: [
        { name: "name", type: "string", required: true },
        { name: "description", type: "string", required: false },
        { name: "parentId", type: "string", required: false },
      ],
      requestExample: [
        `curl -X POST "$API_URL/workspaces/${workspaceId}/projects" \\`,
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        '  -H "Content-Type: application/json" \\',
        "  -d '{ \"name\": \"Website Redesign\" }'",
      ].join("\n"),
      responseStatus: "201 Created",
      responseExample: [
        "{",
        `  "id": "uuid", "workspaceId": "${workspaceId}", "parentId": null, "name": "Website Redesign",`,
        '  "description": null, "status": "ACTIVE", "createdBy": "uuid", "version": 1, "createdAt": "...", "updatedAt": "..."',
        "}",
      ].join("\n"),
    },
    {
      method: "GET",
      path: `/workspaces/${workspaceId}/projects`,
      summary: "Listar projetos do workspace",
      description: "Paginado, cacheado. Retorna todos os projetos (planos, cada um com `parentId`) — monte a árvore no cliente.",
      requestExample: [
        `curl "$API_URL/workspaces/${workspaceId}/projects" \\`,
        '  -H "Authorization: Bearer $ACCESS_TOKEN"',
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "data": [ { "id": "...", "parentId": null, "...": "..." } ], "meta": { "...": "..." } }',
    },
    {
      method: "GET",
      path: "/projects/:projectId",
      summary: "Detalhe de um projeto",
      description: "Cacheado.",
      requestExample: ['curl "$API_URL/projects/PROJECT_ID" \\', '  -H "Authorization: Bearer $ACCESS_TOKEN"'].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "id": "PROJECT_ID", "name": "Website Redesign", "status": "ACTIVE", "...": "..." }',
      errorCodes: ["PROJECT_NOT_FOUND", "FORBIDDEN_WORKSPACE_ACTION"],
    },
    {
      method: "PATCH",
      path: "/projects/:projectId",
      summary: "Editar nome/descrição",
      bodyParams: [
        { name: "name", type: "string", required: false },
        { name: "description", type: "string", required: false },
      ],
      requestExample: [
        'curl -X PATCH "$API_URL/projects/PROJECT_ID" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        '  -H "Content-Type: application/json" \\',
        "  -d '{ \"description\": \"Novo escopo\" }'",
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "id": "PROJECT_ID", "description": "Novo escopo", "...": "..." }',
    },
    {
      method: "PATCH",
      path: "/projects/:projectId/archive",
      summary: "Arquivar",
      description: "Não há \"desarquivar\" nem delete explícito. Bloqueado se o projeto tiver sub-projetos ainda ativos.",
      requestExample: [
        'curl -X PATCH "$API_URL/projects/PROJECT_ID/archive" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN"',
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "id": "PROJECT_ID", "status": "ARCHIVED", "...": "..." }',
      errorCodes: ["PROJECT_HAS_CHILDREN"],
    },
    {
      method: "GET",
      path: "/projects/:projectId/subprojects",
      summary: "Sub-projetos diretos",
      description: "Paginado, cacheado. Um nível só, mais antigos primeiro.",
      requestExample: [
        'curl "$API_URL/projects/PROJECT_ID/subprojects" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN"',
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "data": [ { "id": "...", "parentId": "PROJECT_ID", "...": "..." } ], "meta": { "...": "..." } }',
      errorCodes: ["PROJECT_NOT_FOUND", "FORBIDDEN_WORKSPACE_ACTION"],
    },
    {
      method: "PATCH",
      path: "/projects/:projectId/move",
      summary: "Mover na árvore de projetos",
      bodyParams: [{ name: "parentId", type: "string | null", required: true, notes: "null promove a projeto raiz" }],
      requestExample: [
        'curl -X PATCH "$API_URL/projects/PROJECT_ID/move" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        '  -H "Content-Type: application/json" \\',
        "  -d '{ \"parentId\": null }'",
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "id": "PROJECT_ID", "parentId": null, "...": "..." }',
      notes: [
        "Membership em cascata: quem tem acesso via `ProjectMember` a um projeto ganha acesso a todos os descendentes dele — mover um projeto muda quem tem acesso a ele.",
      ],
      errorCodes: ["CANNOT_BE_OWN_PARENT", "CANNOT_MOVE_INTO_OWN_DESCENDANT", "PARENT_OUT_OF_SCOPE", "PARENT_PROJECT_ARCHIVED", "PROJECT_NOT_FOUND", "FORBIDDEN_WORKSPACE_ACTION"],
    },
    {
      method: "POST",
      path: "/projects/:projectId/invitations",
      summary: "Convidar para o projeto",
      description: "Análogo ao convite de workspace, mas escopado a este projeto (acesso pontual sem entrar no workspace inteiro).",
      bodyParams: [
        { name: "email", type: "string", required: true },
        { name: "role", type: '"MEMBER" | "GUEST"', required: true },
      ],
      requestExample: [
        'curl -X POST "$API_URL/projects/PROJECT_ID/invitations" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        '  -H "Content-Type: application/json" \\',
        "  -d '{ \"email\": \"colaborador@example.com\", \"role\": \"MEMBER\" }'",
      ].join("\n"),
      responseStatus: "201 Created",
      responseExample: '{ "id": "uuid", "projectId": "PROJECT_ID", "email": "colaborador@example.com", "status": "PENDING", "...": "..." }',
    },
    {
      method: "GET",
      path: "/projects/:projectId/invitations",
      summary: "Listar convites do projeto",
      description: "Paginado, cacheado.",
      requestExample: [
        'curl "$API_URL/projects/PROJECT_ID/invitations" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN"',
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "data": [ "..." ], "meta": { "...": "..." } }',
    },
    {
      method: "DELETE",
      path: "/projects/:projectId/invitations/:invitationId",
      summary: "Revogar convite do projeto",
      requestExample: [
        'curl -X DELETE "$API_URL/projects/PROJECT_ID/invitations/INVITATION_ID" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN"',
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "revoked": true }',
      errorCodes: ["INVITATION_NOT_FOUND", "INVITATION_ALREADY_PROCESSED"],
    },
    {
      method: "GET",
      path: "/projects/invitations/:token/preview",
      summary: "Pré-visualizar convite de projeto (público)",
      description: "Igual ao preview de workspace, com `projectId`/`projectName`. Cacheado por 30s.",
      requestExample: ['curl "$API_URL/projects/invitations/TOKEN/preview"'].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "projectId": "PROJECT_ID", "projectName": "Website Redesign", "email": "...", "role": "MEMBER", "status": "PENDING", "expiresAt": "..." }',
      errorCodes: ["INVITATION_NOT_FOUND"],
    },
    {
      method: "POST",
      path: "/projects/invitations/:token/accept",
      summary: "Aceitar convite de projeto",
      requestExample: [
        'curl -X POST "$API_URL/projects/invitations/TOKEN/accept" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN"',
      ].join("\n"),
      responseStatus: "201 Created",
      responseExample: '{ "projectId": "PROJECT_ID", "userId": "uuid", "role": "MEMBER" }',
      errorCodes: ["INVITATION_NOT_FOUND", "INVITATION_EXPIRED", "INVITATION_ALREADY_PROCESSED", "INVITATION_EMAIL_MISMATCH"],
    },
    {
      method: "GET",
      path: "/projects/:projectId/members",
      summary: "Listar membros do projeto",
      description:
        "Paginado, cacheado. Só lista membros diretos (`ProjectMember`) — quem tem acesso só por herança de um projeto ancestral não aparece aqui.",
      requestExample: [
        'curl "$API_URL/projects/PROJECT_ID/members" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN"',
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "data": [ { "userId": "uuid", "name": "Jane Doe", "role": "MEMBER", "createdAt": "..." } ], "meta": { "...": "..." } }',
    },
    {
      method: "DELETE",
      path: "/projects/:projectId/members/:userId",
      summary: "Remover acesso de um membro",
      description: "Só remove membership direta — para tirar acesso herdado, remova o membro no projeto ancestral onde foi adicionado.",
      requestExample: [
        'curl -X DELETE "$API_URL/projects/PROJECT_ID/members/USER_ID" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN"',
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "removed": true }',
      errorCodes: ["MEMBER_NOT_FOUND"],
    },
    {
      method: "POST",
      path: "/projects/:projectId/sections",
      summary: "Criar uma section",
      description:
        "Sempre entra ao final da lista de irmãs (mesmo `parentId`) — nunca `isDefault`, essa nasce sozinha com o projeto. `parentId` opcional cria como sub-seção.",
      bodyParams: [
        { name: "name", type: "string", required: true },
        { name: "parentId", type: "string", required: false },
      ],
      requestExample: [
        'curl -X POST "$API_URL/projects/PROJECT_ID/sections" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        '  -H "Content-Type: application/json" \\',
        "  -d '{ \"name\": \"In Progress\" }'",
      ].join("\n"),
      responseStatus: "201 Created",
      responseExample: [
        "{",
        '  "id": "uuid", "projectId": "PROJECT_ID", "parentId": null, "name": "In Progress",',
        '  "position": 1, "isDefault": false, "version": 1, "createdAt": "...", "updatedAt": "..."',
        "}",
      ].join("\n"),
      errorCodes: ["PROJECT_NOT_FOUND", "SECTION_NOT_FOUND", "PARENT_OUT_OF_SCOPE"],
    },
    {
      method: "GET",
      path: "/projects/:projectId/sections",
      summary: "Listar sections do projeto",
      description: "Paginado, cacheado. Todas as sections (todos os níveis), ordenadas por `position` — monte a árvore agrupando por `parentId`.",
      requestExample: [
        'curl "$API_URL/projects/PROJECT_ID/sections" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN"',
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "data": [ { "id": "...", "position": 0, "...": "..." } ], "meta": { "...": "..." } }',
    },
    {
      method: "PATCH",
      path: "/sections/:sectionId",
      summary: "Renomear/reordenar",
      description: "`position` (0-based) reordena entre as irmãs atuais — sempre clampada, nunca lança erro por estar fora do intervalo.",
      bodyParams: [
        { name: "name", type: "string", required: false },
        { name: "position", type: "number", required: false },
      ],
      requestExample: [
        'curl -X PATCH "$API_URL/sections/SECTION_ID" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        '  -H "Content-Type: application/json" \\',
        "  -d '{ \"position\": 0 }'",
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "id": "SECTION_ID", "position": 0, "...": "..." }',
      errorCodes: ["SECTION_NOT_FOUND"],
    },
    {
      method: "PATCH",
      path: "/sections/:sectionId/move",
      summary: "Mover para outro pai",
      bodyParams: [
        { name: "parentId", type: "string | null", required: true },
        { name: "position", type: "number", required: false, notes: "omitido entra ao final" },
      ],
      requestExample: [
        'curl -X PATCH "$API_URL/sections/SECTION_ID/move" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        '  -H "Content-Type: application/json" \\',
        "  -d '{ \"parentId\": null }'",
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "id": "SECTION_ID", "parentId": null, "...": "..." }',
      errorCodes: ["CANNOT_BE_OWN_PARENT", "CANNOT_MOVE_INTO_OWN_DESCENDANT", "PARENT_OUT_OF_SCOPE", "SECTION_NOT_FOUND", "FORBIDDEN_WORKSPACE_ACTION"],
    },
    {
      method: "DELETE",
      path: "/sections/:sectionId",
      summary: "Apagar",
      description: "Bloqueado se for a section padrão, se tiver sub-seções, ou se ainda tiver tasks.",
      requestExample: [
        'curl -X DELETE "$API_URL/sections/SECTION_ID" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN"',
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "deleted": true, "projectId": "PROJECT_ID" }',
      errorCodes: ["DEFAULT_SECTION_NOT_DELETABLE", "SECTION_HAS_CHILDREN", "SECTION_NOT_EMPTY"],
    },
  ];
}
