import type { ApiEndpoint } from "@/features/developers/lib/api-reference-data";

const TASK_DTO_STUB =
  '{ "id": "TASK_ID", "projectId": "PROJECT_ID", "sectionId": "SECTION_ID", "position": 0, "parentTaskId": null, "title": "Fix login bug", "description": null, "status": "TODO", "assigneeId": null, "dueDate": null, "priority": null, "createdBy": "uuid", "version": 1, "hasCover": false, "coverUrl": null, "attachments": [], "participantIds": [], "mentionedUserIds": [], "...": "..." }';

// API.md § 9 (Tasks) — o maior grupo de rotas da API, tudo escopado a
// projeto/task, sem depender do workspaceId da página. Custom fields e
// comments (§ 10-11) ficam em `buildCustomFieldEndpoints`/`buildCommentEndpoints`
// abaixo, para a UI apresentá-los como sub-seções separadas.
export function buildTaskEndpoints(): ApiEndpoint[] {
  return [
    {
      method: "POST",
      path: "/projects/:projectId/tasks",
      summary: "Criar uma task",
      description:
        "`sectionId` omitido usa a section padrão do projeto. `position` é sempre atribuída ao final da lista — para escolher a posição, crie e reordene em seguida via `PATCH`.",
      bodyParams: [
        { name: "title", type: "string", required: true },
        { name: "sectionId", type: "string", required: false, notes: "padrão: section padrão do projeto" },
        { name: "description", type: "string", required: false },
        { name: "assigneeId", type: "string", required: false },
        { name: "parentTaskId", type: "string", required: false, notes: "cria como subtask" },
        { name: "dueDate", type: "string (ISO 8601)", required: false },
        { name: "priority", type: '"LOW" | "MEDIUM" | "HIGH" | "URGENT"', required: false },
        { name: "mentionedUserIds", type: "string[]", required: false, notes: "até 50 uuids" },
      ],
      requestExample: [
        'curl -X POST "$API_URL/projects/PROJECT_ID/tasks" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        '  -H "Content-Type: application/json" \\',
        "  -d '{ \"title\": \"Fix login bug\" }'",
      ].join("\n"),
      responseStatus: "201 Created",
      responseExample: TASK_DTO_STUB,
      errorCodes: ["SUBTASK_PROJECT_MISMATCH", "SECTION_NOT_FOUND", "SECTION_PROJECT_MISMATCH", "ASSIGNEE_NOT_PROJECT_MEMBER", "MENTIONED_USER_NOT_PROJECT_MEMBER"],
    },
    {
      method: "GET",
      path: "/projects/:projectId/tasks",
      summary: "Listar tasks de nível superior",
      description: "Paginado, cacheado. Tipicamente as tasks que não são subtask de nenhuma outra.",
      requestExample: [
        'curl "$API_URL/projects/PROJECT_ID/tasks" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN"',
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: `{ "data": [ ${TASK_DTO_STUB} ], "meta": { "...": "..." } }`,
    },
    {
      method: "GET",
      path: "/sections/:sectionId/tasks",
      summary: "Listar tasks de uma section",
      description: "Paginado, cacheado. Visão tipo Kanban — vem ordenado por `position` ascendente, renderize direto.",
      requestExample: [
        'curl "$API_URL/sections/SECTION_ID/tasks" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN"',
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: `{ "data": [ ${TASK_DTO_STUB} ], "meta": { "...": "..." } }`,
      errorCodes: ["SECTION_NOT_FOUND"],
    },
    {
      method: "GET",
      path: "/tasks/:taskId",
      summary: "Detalhe de uma task",
      description: "Cacheado.",
      requestExample: ['curl "$API_URL/tasks/TASK_ID" \\', '  -H "Authorization: Bearer $ACCESS_TOKEN"'].join("\n"),
      responseStatus: "200 OK",
      responseExample: TASK_DTO_STUB,
      errorCodes: ["TASK_NOT_FOUND"],
    },
    {
      method: "GET",
      path: "/tasks/:taskId/subtasks",
      summary: "Listar subtasks diretas",
      description: "Paginado, cacheado.",
      requestExample: [
        'curl "$API_URL/tasks/TASK_ID/subtasks" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN"',
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: `{ "data": [ ${TASK_DTO_STUB} ], "meta": { "...": "..." } }`,
    },
    {
      method: "PATCH",
      path: "/tasks/:taskId",
      summary: "Editar/mover/reparentar",
      description:
        "`sectionId`+`position` move e reordena numa chamada só; `parentTaskId` reparenta (`null` promove a task de topo). `mentionedUserIds` substitui o conjunto atual de menções (`[]` remove todas, omitido não altera). Não é possível limpar `dueDate`/`priority`/`assigneeId` (`null`) por esta rota — só via sync.",
      bodyParams: [
        { name: "title", type: "string", required: false },
        { name: "description", type: "string", required: false },
        { name: "assigneeId", type: "string", required: false },
        { name: "sectionId", type: "string", required: false },
        { name: "position", type: "number", required: false, notes: "0-based, sempre clampada" },
        { name: "dueDate", type: "string (ISO 8601)", required: false },
        { name: "priority", type: '"LOW" | "MEDIUM" | "HIGH" | "URGENT"', required: false },
        { name: "parentTaskId", type: "string | null", required: false },
        { name: "mentionedUserIds", type: "string[]", required: false },
      ],
      requestExample: [
        'curl -X PATCH "$API_URL/tasks/TASK_ID" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        '  -H "Content-Type: application/json" \\',
        "  -d '{ \"sectionId\": \"SECTION_ID\", \"position\": 0 }'",
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: TASK_DTO_STUB,
      errorCodes: ["SECTION_NOT_FOUND", "SECTION_PROJECT_MISMATCH", "MENTIONED_USER_NOT_PROJECT_MEMBER", "ASSIGNEE_NOT_PROJECT_MEMBER", "TASK_NOT_FOUND", "SUBTASK_PROJECT_MISMATCH", "CANNOT_BE_OWN_PARENT", "CANNOT_MOVE_INTO_OWN_DESCENDANT"],
    },
    {
      method: "PATCH",
      path: "/tasks/:taskId/status",
      summary: "Mudar status",
      description: "Não é permitido concluir (`DONE`) uma task com subtasks pendentes.",
      bodyParams: [{ name: "status", type: '"TODO" | "IN_PROGRESS" | "DONE"', required: true }],
      requestExample: [
        'curl -X PATCH "$API_URL/tasks/TASK_ID/status" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        '  -H "Content-Type: application/json" \\',
        "  -d '{ \"status\": \"IN_PROGRESS\" }'",
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: TASK_DTO_STUB,
      errorCodes: ["TASK_HAS_PENDING_SUBTASKS"],
    },
    {
      method: "POST",
      path: "/tasks/:taskId/attachments",
      summary: "Upload de anexo",
      description: "`multipart/form-data`, campo `file`. Limite de 20MB.",
      requestExample: [
        'curl -X POST "$API_URL/tasks/TASK_ID/attachments" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        '  -F "file=@screenshot.png"',
      ].join("\n"),
      responseStatus: "201 Created",
      responseExample: TASK_DTO_STUB,
    },
    {
      method: "GET",
      path: "/tasks/:taskId/attachments/:attachmentId/download",
      summary: "Baixar um anexo",
      description: "Binário com `Content-Disposition: attachment` — trate como download direto (fetch + blob, já que é rota protegida por JWT).",
      requestExample: [
        'curl "$API_URL/tasks/TASK_ID/attachments/ATTACHMENT_ID/download" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        "  --output arquivo",
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: "(binário)",
      errorCodes: ["TASK_NOT_FOUND", "ATTACHMENT_NOT_FOUND"],
    },
    {
      method: "DELETE",
      path: "/tasks/:taskId/attachments/:attachmentId",
      summary: "Remover um anexo",
      description: "Requer papel diferente de `GUEST` no projeto.",
      requestExample: [
        'curl -X DELETE "$API_URL/tasks/TASK_ID/attachments/ATTACHMENT_ID" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN"',
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: TASK_DTO_STUB,
      errorCodes: ["TASK_NOT_FOUND", "ATTACHMENT_NOT_FOUND", "FORBIDDEN_WORKSPACE_ACTION"],
    },
    {
      method: "PUT",
      path: "/tasks/:taskId/cover",
      summary: "Definir/trocar a capa",
      description: "`multipart/form-data`, campo `file`. Limite de 10MB, JPEG/PNG/WebP pelo conteúdo. Trocar apaga a anterior do storage.",
      requestExample: [
        'curl -X PUT "$API_URL/tasks/TASK_ID/cover" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        '  -F "file=@capa.jpg"',
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: TASK_DTO_STUB,
      errorCodes: ["INVALID_TASK_COVER", "TASK_NOT_FOUND", "FORBIDDEN_WORKSPACE_ACTION"],
    },
    {
      method: "GET",
      path: "/tasks/:taskId/cover",
      summary: "Baixar a capa",
      description: "Qualquer papel com acesso ao projeto pode ler (inclusive `GUEST`).",
      requestExample: [
        'curl "$API_URL/tasks/TASK_ID/cover" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        "  --output capa.jpg",
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: "(binário)",
      errorCodes: ["TASK_NOT_FOUND", "TASK_COVER_NOT_FOUND", "FORBIDDEN_WORKSPACE_ACTION"],
    },
    {
      method: "DELETE",
      path: "/tasks/:taskId/cover",
      summary: "Remover a capa",
      description: "Idempotente — numa task sem capa devolve a task como está.",
      requestExample: ['curl -X DELETE "$API_URL/tasks/TASK_ID/cover" \\', '  -H "Authorization: Bearer $ACCESS_TOKEN"'].join(
        "\n",
      ),
      responseStatus: "200 OK",
      responseExample: TASK_DTO_STUB,
      errorCodes: ["TASK_NOT_FOUND", "FORBIDDEN_WORKSPACE_ACTION"],
    },
    {
      method: "POST",
      path: "/projects/:projectId/tasks/bulk",
      summary: "Criar tasks em lote",
      description: "Até 100 itens. Sucesso parcial sempre 200 — cada item processa exatamente como `POST /projects/:projectId/tasks`, na ordem enviada.",
      bodyParams: [{ name: "tasks", type: "CreateTaskDto[]", required: true, notes: "máx. 100" }],
      requestExample: [
        'curl -X POST "$API_URL/projects/PROJECT_ID/tasks/bulk" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        '  -H "Content-Type: application/json" \\',
        "  -d '{ \"tasks\": [{ \"title\": \"Tarefa 1\" }, { \"title\": \"Tarefa 2\" }] }'",
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: [
        "{",
        '  "total": 2, "succeeded": 2, "failed": 0,',
        '  "results": [',
        '    { "index": 0, "taskId": "uuid", "status": "SUCCESS", "data": { "...": "TaskDto" } },',
        '    { "index": 1, "taskId": "uuid", "status": "SUCCESS", "data": { "...": "TaskDto" } }',
        "  ]",
        "}",
      ].join("\n"),
      notes: ["Um erro por item nunca desfaz os itens que já passaram (sem rollback)."],
      errorCodes: ["BULK_BATCH_TOO_LARGE"],
    },
    {
      method: "PATCH",
      path: "/tasks/bulk",
      summary: "Editar tasks em lote",
      description: "Até 100 itens, cada um um `PATCH /tasks/:taskId` completo. Não escopado a um projeto — um lote pode misturar projetos.",
      bodyParams: [{ name: "tasks", type: "({ taskId } & UpdateTaskDto)[]", required: true, notes: "máx. 100" }],
      requestExample: [
        'curl -X PATCH "$API_URL/tasks/bulk" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        '  -H "Content-Type: application/json" \\',
        "  -d '{ \"tasks\": [{ \"taskId\": \"uuid\", \"status\": \"DONE\" }] }'",
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "total": 1, "succeeded": 1, "failed": 0, "results": [ { "index": 0, "taskId": "uuid", "status": "SUCCESS", "data": { "...": "..." } } ] }',
      errorCodes: ["BULK_BATCH_TOO_LARGE"],
    },
    {
      method: "POST",
      path: "/tasks/bulk-delete",
      summary: "Remover tasks em lote",
      description: "Soft delete e leva junto todas as subtasks (qualquer profundidade). Não existe `DELETE /tasks/:taskId` unitário — mande um id só aqui para isso.",
      bodyParams: [{ name: "taskIds", type: "string[]", required: true, notes: "sem repetição, máx. 100" }],
      requestExample: [
        'curl -X POST "$API_URL/tasks/bulk-delete" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        '  -H "Content-Type: application/json" \\',
        "  -d '{ \"taskIds\": [\"uuid\"] }'",
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "total": 1, "succeeded": 1, "failed": 0, "results": [ { "index": 0, "taskId": "uuid", "status": "SUCCESS", "data": { "id": "uuid", "projectId": "...", "deletedSubtaskIds": [] } } ] }',
      errorCodes: ["BULK_BATCH_TOO_LARGE"],
    },
    {
      method: "POST",
      path: "/tasks/:taskId/participants",
      summary: "Adicionar participante",
      description: "Aditivo a `assigneeId`, sem hierarquia. Idempotente: adicionar quem já é participante é um no-op.",
      bodyParams: [{ name: "userId", type: "string", required: true }],
      requestExample: [
        'curl -X POST "$API_URL/tasks/TASK_ID/participants" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        '  -H "Content-Type: application/json" \\',
        "  -d '{ \"userId\": \"uuid\" }'",
      ].join("\n"),
      responseStatus: "201 Created",
      responseExample: TASK_DTO_STUB,
      errorCodes: ["TASK_NOT_FOUND", "ASSIGNEE_NOT_PROJECT_MEMBER"],
    },
    {
      method: "DELETE",
      path: "/tasks/:taskId/participants/:userId",
      summary: "Remover participante",
      description: "Idempotente: remover quem já não é participante é um no-op.",
      requestExample: [
        'curl -X DELETE "$API_URL/tasks/TASK_ID/participants/USER_ID" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN"',
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: TASK_DTO_STUB,
      errorCodes: ["TASK_NOT_FOUND"],
    },
  ];
}

// API.md § 10 (Custom Fields).
export function buildCustomFieldEndpoints(): ApiEndpoint[] {
  return [
    {
      method: "POST",
      path: "/projects/:projectId/custom-fields",
      summary: "Criar um campo personalizado",
      bodyParams: [
        { name: "name", type: "string", required: true },
        { name: "type", type: '"TEXT"|"NUMBER"|"DATE"|"SINGLE_SELECT"|"MULTI_SELECT"|"CHECKBOX"|"PEOPLE"', required: true },
        { name: "options", type: "string[]", required: false, notes: "obrigatório na prática para SINGLE_SELECT/MULTI_SELECT" },
      ],
      requestExample: [
        'curl -X POST "$API_URL/projects/PROJECT_ID/custom-fields" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        '  -H "Content-Type: application/json" \\',
        "  -d '{ \"name\": \"Priority\", \"type\": \"SINGLE_SELECT\", \"options\": [\"Low\",\"Medium\",\"High\"] }'",
      ].join("\n"),
      responseStatus: "201 Created",
      responseExample: '{ "id": "uuid", "projectId": "PROJECT_ID", "name": "Priority", "type": "SINGLE_SELECT", "options": ["Low","Medium","High"], "archived": false, "version": 1 }',
    },
    {
      method: "GET",
      path: "/projects/:projectId/custom-fields",
      summary: "Listar campos personalizados",
      description: "Paginado, cacheado.",
      requestExample: [
        'curl "$API_URL/projects/PROJECT_ID/custom-fields" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN"',
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "data": [ { "id": "...", "type": "SINGLE_SELECT", "...": "..." } ], "meta": { "...": "..." } }',
    },
    {
      method: "PATCH",
      path: "/custom-fields/:definitionId/options",
      summary: "Atualizar as opções",
      bodyParams: [{ name: "options", type: "string[]", required: true }],
      requestExample: [
        'curl -X PATCH "$API_URL/custom-fields/DEFINITION_ID/options" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        '  -H "Content-Type: application/json" \\',
        "  -d '{ \"options\": [\"Low\",\"Medium\",\"High\",\"Critical\"] }'",
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "id": "DEFINITION_ID", "options": ["Low","Medium","High","Critical"], "...": "..." }',
      errorCodes: ["CUSTOM_FIELD_NOT_FOUND"],
    },
    {
      method: "PATCH",
      path: "/custom-fields/:definitionId/archive",
      summary: "Arquivar",
      description: "Não pode mais ser usado/editado, mas valores existentes permanecem.",
      requestExample: [
        'curl -X PATCH "$API_URL/custom-fields/DEFINITION_ID/archive" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN"',
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "id": "DEFINITION_ID", "archived": true, "...": "..." }',
    },
    {
      method: "GET",
      path: "/tasks/:taskId/custom-field-values",
      summary: "Listar valores preenchidos numa task",
      description: "Paginado, cacheado. `value` é polimórfico conforme o `type` da definição.",
      requestExample: [
        'curl "$API_URL/tasks/TASK_ID/custom-field-values" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN"',
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "data": [ { "id": "uuid", "taskId": "TASK_ID", "fieldDefinitionId": "uuid", "value": "High", "updatedAt": "..." } ], "meta": { "...": "..." } }',
    },
    {
      method: "PATCH",
      path: "/tasks/:taskId/custom-field-values/:definitionId",
      summary: "Definir/atualizar um valor",
      bodyParams: [{ name: "value", type: "string | number | boolean | string[]", required: true, notes: "conforme o type da definição" }],
      requestExample: [
        'curl -X PATCH "$API_URL/tasks/TASK_ID/custom-field-values/DEFINITION_ID" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        '  -H "Content-Type: application/json" \\',
        "  -d '{ \"value\": \"High\" }'",
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "id": "uuid", "taskId": "TASK_ID", "fieldDefinitionId": "DEFINITION_ID", "value": "High", "updatedAt": "..." }',
      errorCodes: ["CUSTOM_FIELD_VALUE_INVALID", "CUSTOM_FIELD_NOT_FOUND", "TASK_NOT_FOUND"],
    },
  ];
}

// API.md § 11 (Comments).
export function buildCommentEndpoints(): ApiEndpoint[] {
  return [
    {
      method: "POST",
      path: "/tasks/:taskId/comments",
      summary: "Comentar (ou responder)",
      description: "`parentId` opcional responde a outro comentário (threading de profundidade arbitrária) — o pai precisa ser da mesma task.",
      bodyParams: [
        { name: "content", type: "string", required: true, notes: "1 a 5000 caracteres" },
        { name: "parentId", type: "string", required: false },
        { name: "mentionedUserIds", type: "string[]", required: false, notes: "até 50 uuids" },
      ],
      requestExample: [
        'curl -X POST "$API_URL/tasks/TASK_ID/comments" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        '  -H "Content-Type: application/json" \\',
        "  -d '{ \"content\": \"This looks good to me.\" }'",
      ].join("\n"),
      responseStatus: "201 Created",
      responseExample: '{ "id": "uuid", "taskId": "TASK_ID", "parentId": null, "authorId": "uuid", "content": "This looks good to me.", "mentionedUserIds": [], "createdAt": "...", "updatedAt": "..." }',
      errorCodes: ["TASK_NOT_FOUND", "MENTIONED_USER_NOT_PROJECT_MEMBER", "COMMENT_NOT_FOUND", "PARENT_OUT_OF_SCOPE", "COMMENT_CONTENT_INVALID", "FORBIDDEN_WORKSPACE_ACTION"],
    },
    {
      method: "GET",
      path: "/tasks/:taskId/comments",
      summary: "Listar comentários",
      description: "Paginado, cacheado, ordenado por `createdAt` ascendente. Lista plana com `parentId` — monte a thread no cliente.",
      requestExample: [
        'curl "$API_URL/tasks/TASK_ID/comments" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN"',
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "data": [ { "id": "...", "parentId": null, "...": "..." } ], "meta": { "...": "..." } }',
      errorCodes: ["TASK_NOT_FOUND", "FORBIDDEN_WORKSPACE_ACTION"],
    },
    {
      method: "DELETE",
      path: "/comments/:commentId",
      summary: "Apagar (hard delete)",
      description: "Sem edição nesta versão. Só o autor ou um `OWNER`/`ADMIN` do workspace pode apagar. Bloqueado se ainda tiver respostas.",
      requestExample: [
        'curl -X DELETE "$API_URL/comments/COMMENT_ID" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN"',
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "id": "COMMENT_ID", "taskId": "TASK_ID" }',
      errorCodes: ["COMMENT_NOT_FOUND", "COMMENT_AUTHOR_MISMATCH", "COMMENT_HAS_CHILDREN"],
    },
  ];
}
