import type { ApiEndpoint } from "@/features/developers/lib/api-reference-data";

// API.md § 4-5 (Workspaces + Convites de Workspace).
export function buildWorkspaceEndpoints(workspaceId: string): ApiEndpoint[] {
  return [
    {
      method: "POST",
      path: "/workspaces",
      summary: "Criar um workspace",
      description: "O criador vira `OWNER` automaticamente.",
      bodyParams: [{ name: "name", type: "string", required: true, notes: "mín. 2 caracteres" }],
      requestExample: [
        'curl -X POST "$API_URL/workspaces" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        '  -H "Content-Type: application/json" \\',
        "  -d '{ \"name\": \"Marketing Team\" }'",
      ].join("\n"),
      responseStatus: "201 Created",
      responseExample: [
        "{",
        '  "id": "uuid", "name": "Marketing Team", "ownerId": "uuid", "assistantEnabled": false,',
        '  "members": [{ "userId": "uuid", "name": "Jane Doe", "role": "OWNER", "createdAt": "..." }],',
        '  "version": 1, "createdAt": "...", "updatedAt": "..."',
        "}",
      ].join("\n"),
    },
    {
      method: "GET",
      path: "/workspaces",
      summary: "Listar meus workspaces",
      description: "Paginado, cacheado. Workspaces dos quais o usuário autenticado é membro.",
      queryParams: [
        { name: "page", type: "number", required: false },
        { name: "limit", type: "number", required: false, notes: "máx. 100" },
      ],
      requestExample: ['curl "$API_URL/workspaces" \\', '  -H "Authorization: Bearer $ACCESS_TOKEN"'].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "data": [ { "id": "...", "name": "...", "...": "..." } ], "meta": { "page": 1, "limit": 20, "total": 1, "totalPages": 1 } }',
    },
    {
      method: "GET",
      path: `/workspaces/${workspaceId}`,
      summary: "Detalhe do workspace",
      description: "Cacheado. Requer ser membro (qualquer papel).",
      requestExample: [
        `curl "$API_URL/workspaces/${workspaceId}" \\`,
        '  -H "Authorization: Bearer $ACCESS_TOKEN"',
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: `{ "id": "${workspaceId}", "name": "Marketing Team", "ownerId": "uuid", "members": [ "..." ], "...": "..." }`,
      errorCodes: ["WORKSPACE_NOT_FOUND", "FORBIDDEN_WORKSPACE_ACTION"],
    },
    {
      method: "PATCH",
      path: `/workspaces/${workspaceId}`,
      summary: "Renomear",
      description: "Requer `ADMIN`/`OWNER`.",
      bodyParams: [{ name: "name", type: "string", required: true }],
      requestExample: [
        `curl -X PATCH "$API_URL/workspaces/${workspaceId}" \\`,
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        '  -H "Content-Type: application/json" \\',
        "  -d '{ \"name\": \"Growth Team\" }'",
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: `{ "id": "${workspaceId}", "name": "Growth Team", "...": "..." }`,
      errorCodes: ["WORKSPACE_NOT_FOUND", "FORBIDDEN_WORKSPACE_ACTION"],
    },
    {
      method: "DELETE",
      path: `/workspaces/${workspaceId}`,
      summary: "Excluir (soft delete)",
      description:
        "Irreversível pela API — não existe reabrir. Requer papel `OWNER` (mais restrito que renomear). Só é permitido quando o workspace não tem nenhum outro membro além do OWNER solicitante.",
      requestExample: [
        `curl -X DELETE "$API_URL/workspaces/${workspaceId}" \\`,
        '  -H "Authorization: Bearer $ACCESS_TOKEN"',
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: `{ "deleted": true, "workspaceId": "${workspaceId}" }`,
      errorCodes: ["WORKSPACE_NOT_FOUND", "FORBIDDEN_WORKSPACE_ACTION", "WORKSPACE_NOT_EMPTY"],
    },
    {
      method: "POST",
      path: `/workspaces/${workspaceId}/members`,
      summary: "Adicionar membro por userId",
      description:
        "Sem fluxo de convite — uso administrativo direto (para convidar por e-mail, ver a seção de convites abaixo). Conceder `role: OWNER` exige que quem chama já seja `OWNER`.",
      bodyParams: [
        { name: "userId", type: "string", required: true },
        { name: "role", type: '"OWNER" | "ADMIN" | "MEMBER" | "GUEST"', required: true },
      ],
      requestExample: [
        `curl -X POST "$API_URL/workspaces/${workspaceId}/members" \\`,
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        '  -H "Content-Type: application/json" \\',
        "  -d '{ \"userId\": \"uuid\", \"role\": \"MEMBER\" }'",
      ].join("\n"),
      responseStatus: "201 Created",
      responseExample: `{ "id": "${workspaceId}", "members": [ "..." ], "...": "..." }`,
      errorCodes: ["MEMBER_ALREADY_EXISTS", "FORBIDDEN_WORKSPACE_ACTION"],
    },
    {
      method: "PATCH",
      path: `/workspaces/${workspaceId}/members/:memberId`,
      summary: "Mudar papel de um membro",
      description: "Promover a `OWNER` também exige que quem chama já seja `OWNER`.",
      bodyParams: [{ name: "role", type: '"OWNER" | "ADMIN" | "MEMBER" | "GUEST"', required: true }],
      requestExample: [
        `curl -X PATCH "$API_URL/workspaces/${workspaceId}/members/MEMBER_ID" \\`,
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        '  -H "Content-Type: application/json" \\',
        "  -d '{ \"role\": \"ADMIN\" }'",
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: `{ "id": "${workspaceId}", "members": [ "..." ], "...": "..." }`,
      errorCodes: ["LAST_OWNER_CANNOT_BE_REMOVED", "MEMBER_NOT_FOUND", "FORBIDDEN_WORKSPACE_ACTION"],
    },
    {
      method: "DELETE",
      path: `/workspaces/${workspaceId}/members/:memberId`,
      summary: "Remover um membro",
      requestExample: [
        `curl -X DELETE "$API_URL/workspaces/${workspaceId}/members/MEMBER_ID" \\`,
        '  -H "Authorization: Bearer $ACCESS_TOKEN"',
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: `{ "id": "${workspaceId}", "members": [ "..." ], "...": "..." }`,
      errorCodes: ["LAST_OWNER_CANNOT_BE_REMOVED", "MEMBER_NOT_FOUND"],
    },
    {
      method: "PATCH",
      path: `/workspaces/${workspaceId}/assistant-settings`,
      summary: "Ligar/desligar o assistente de IA",
      description:
        "Requer `OWNER` (mais restrito que renomear/gerenciar membros). Todo workspace novo nasce desligado; reativar depois de um kill switch automático (§ 16) também passa por aqui.",
      bodyParams: [{ name: "enabled", type: "boolean", required: true }],
      requestExample: [
        `curl -X PATCH "$API_URL/workspaces/${workspaceId}/assistant-settings" \\`,
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        '  -H "Content-Type: application/json" \\',
        "  -d '{ \"enabled\": true }'",
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "enabled": true }',
      errorCodes: ["WORKSPACE_NOT_FOUND", "FORBIDDEN_WORKSPACE_ACTION"],
    },
    {
      method: "POST",
      path: `/workspaces/${workspaceId}/invitations`,
      summary: "Convidar por e-mail",
      description: "`OWNER` não pode ser concedido por convite — só `ADMIN`/`MEMBER`/`GUEST`. Expira em 7 dias por padrão.",
      bodyParams: [
        { name: "email", type: "string", required: true },
        { name: "role", type: '"ADMIN" | "MEMBER" | "GUEST"', required: true },
      ],
      requestExample: [
        `curl -X POST "$API_URL/workspaces/${workspaceId}/invitations" \\`,
        '  -H "Authorization: Bearer $ACCESS_TOKEN" \\',
        '  -H "Content-Type: application/json" \\',
        "  -d '{ \"email\": \"novo@example.com\", \"role\": \"MEMBER\" }'",
      ].join("\n"),
      responseStatus: "201 Created",
      responseExample: [
        "{",
        `  "id": "uuid", "workspaceId": "${workspaceId}", "email": "novo@example.com",`,
        '  "role": "MEMBER", "status": "PENDING", "invitedBy": "uuid", "createdAt": "...", "expiresAt": "..."',
        "}",
      ].join("\n"),
    },
    {
      method: "GET",
      path: `/workspaces/${workspaceId}/invitations`,
      summary: "Listar convites",
      description: "Paginado, cacheado. Requer `ADMIN`/`OWNER`.",
      requestExample: [
        `curl "$API_URL/workspaces/${workspaceId}/invitations" \\`,
        '  -H "Authorization: Bearer $ACCESS_TOKEN"',
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "data": [ { "id": "...", "status": "PENDING", "...": "..." } ], "meta": { "...": "..." } }',
    },
    {
      method: "DELETE",
      path: `/workspaces/${workspaceId}/invitations/:invitationId`,
      summary: "Revogar um convite pendente",
      requestExample: [
        `curl -X DELETE "$API_URL/workspaces/${workspaceId}/invitations/INVITATION_ID" \\`,
        '  -H "Authorization: Bearer $ACCESS_TOKEN"',
      ].join("\n"),
      responseStatus: "200 OK",
      responseExample: '{ "revoked": true }',
      errorCodes: ["INVITATION_NOT_FOUND", "INVITATION_ALREADY_PROCESSED"],
    },
    {
      method: "GET",
      path: "/workspaces/invitations/:token/preview",
      summary: "Pré-visualizar convite (público)",
      description:
        "Sem autenticação — usado na página pública de aceite, antes do login. `token` é o do link de e-mail, não o `invitationId`. Cacheado por 30s.",
      requestExample: ['curl "$API_URL/workspaces/invitations/TOKEN/preview"'].join("\n"),
      responseStatus: "200 OK",
      responseExample: [
        "{",
        `  "workspaceId": "${workspaceId}", "workspaceName": "Marketing Team",`,
        '  "email": "novo@example.com", "role": "MEMBER", "status": "PENDING", "expiresAt": "..."',
        "}",
      ].join("\n"),
      errorCodes: ["INVITATION_NOT_FOUND"],
    },
    {
      method: "POST",
      path: "/workspaces/invitations/:token/accept",
      summary: "Aceitar convite",
      description: "Precisa estar logado com o e-mail convidado.",
      requestExample: [
        'curl -X POST "$API_URL/workspaces/invitations/TOKEN/accept" \\',
        '  -H "Authorization: Bearer $ACCESS_TOKEN"',
      ].join("\n"),
      responseStatus: "201 Created",
      responseExample: `{ "id": "${workspaceId}", "members": [ "..." ], "...": "..." }`,
      errorCodes: ["INVITATION_NOT_FOUND", "INVITATION_EXPIRED", "INVITATION_ALREADY_PROCESSED", "INVITATION_EMAIL_MISMATCH"],
    },
  ];
}
