export type ErrorCode =
  | "INVALID_CREDENTIALS"
  | "USER_ALREADY_EXISTS"
  | "CHALLENGE_NOT_FOUND"
  | "CHALLENGE_EXPIRED"
  | "CHALLENGE_INVALID_CODE"
  | "CHALLENGE_MAX_ATTEMPTS_EXCEEDED"
  | "SESSION_NOT_FOUND"
  | "SESSION_EXPIRED"
  | "USER_NOT_FOUND"
  | "USER_ALREADY_CLOSED"
  | "INVALID_USER_PHOTO"
  | "USER_PHOTO_NOT_FOUND"
  | "EMAIL_NOT_VERIFIED"
  | "EMAIL_ALREADY_VERIFIED"
  | "EMAIL_VERIFICATION_NOT_FOUND"
  | "EMAIL_VERIFICATION_EXPIRED"
  | "EMAIL_VERIFICATION_INVALID_CODE"
  | "EMAIL_VERIFICATION_MAX_ATTEMPTS_EXCEEDED"
  | "TOO_MANY_VERIFICATION_REQUESTS"
  | "WORKSPACE_NOT_FOUND"
  | "FORBIDDEN_WORKSPACE_ACTION"
  | "MEMBER_ALREADY_EXISTS"
  | "MEMBER_NOT_FOUND"
  | "LAST_OWNER_CANNOT_BE_REMOVED"
  | "WORKSPACE_NOT_EMPTY"
  | "INVITATION_NOT_FOUND"
  | "INVITATION_ALREADY_PROCESSED"
  | "INVITATION_EXPIRED"
  | "INVITATION_EMAIL_MISMATCH"
  | "PROJECT_NOT_FOUND"
  | "TASK_NOT_FOUND"
  | "BULK_BATCH_TOO_LARGE"
  | "ATTACHMENT_NOT_FOUND"
  | "INVALID_TASK_COVER"
  | "TASK_COVER_NOT_FOUND"
  | "SUBTASK_PROJECT_MISMATCH"
  | "TASK_HAS_PENDING_SUBTASKS"
  | "SECTION_NOT_FOUND"
  | "SECTION_PROJECT_MISMATCH"
  | "DEFAULT_SECTION_NOT_DELETABLE"
  | "SECTION_NOT_EMPTY"
  | "CANNOT_BE_OWN_PARENT"
  | "CANNOT_MOVE_INTO_OWN_DESCENDANT"
  | "PARENT_OUT_OF_SCOPE"
  | "PARENT_PROJECT_ARCHIVED"
  | "PROJECT_HAS_CHILDREN"
  | "SECTION_HAS_CHILDREN"
  | "COMMENT_HAS_CHILDREN"
  | "ASSIGNEE_NOT_PROJECT_MEMBER"
  | "MENTIONED_USER_NOT_PROJECT_MEMBER"
  | "CUSTOM_FIELD_NOT_FOUND"
  | "CUSTOM_FIELD_VALUE_INVALID"
  | "SYNC_VERSION_CONFLICT"
  | "CLIENT_NOT_FOUND"
  | "CANNOT_MODIFY_OWN_ACCOUNT"
  | "COMMENT_NOT_FOUND"
  | "COMMENT_CONTENT_INVALID"
  | "COMMENT_AUTHOR_MISMATCH"
  | "INVALID_ANALYTICS_QUERY"
  | "AI_ASSISTANT_RATE_LIMIT_EXCEEDED"
  | "AI_ASSISTANT_TRANSLATION_FAILED"
  | "PENDING_ACTION_NOT_FOUND"
  | "PENDING_ACTION_EXPIRED"
  | "REAUTHENTICATION_REQUIRED"
  | "ASSISTANT_DISABLED_FOR_WORKSPACE"
  | "ASSISTANT_ATTACHMENT_TOO_LARGE"
  | "ASSISTANT_ATTACHMENTS_TOO_LARGE"
  | "ASSISTANT_TOO_MANY_ATTACHMENTS"
  | "ASSISTANT_AUDIO_TOO_LONG"
  | "ASSISTANT_TRANSCRIPTION_FAILED"
  | "ASSISTANT_EMPTY_TRANSCRIPTION"
  | "AI_TRANSLATION_FAILED"
  | "AI_INSUFFICIENT_CREDITS"
  | "AI_RATE_LIMIT_EXCEEDED"
  | "ACCOUNT_HAS_NO_PASSWORD"
  | "CURRENT_PASSWORD_INCORRECT"
  | "ACCOUNT_ALREADY_HAS_PASSWORD"
  | "NO_IDENTITY_METHOD_AVAILABLE"
  | "INVALID_GOOGLE_TOKEN"
  | "GOOGLE_ACCOUNT_ALREADY_LINKED"
  | "INVALID_PASSWORD_RESET_TOKEN"
  | "TOO_MANY_PASSWORD_RESET_REQUESTS"
  | "INVALID_AUTOMATION_TRIGGER"
  | "INVALID_AUTOMATION_ACTION"
  | "AUTOMATION_RULE_NOT_FOUND"
  | "AI_USAGE_INVALID_RANGE"
  | "API_KEY_NOT_FOUND"
  | "INVALID_API_KEY_SCOPE"
  | "WEBHOOK_ENDPOINT_NOT_FOUND"
  | "WEBHOOK_DELIVERY_NOT_FOUND"
  | "WEBHOOK_ENDPOINT_URL_NOT_ALLOWED"
  | "INVALID_WEBHOOK_EVENT"
  | "PLAN_NOT_FOUND"
  | "PLAN_NAME_ALREADY_EXISTS"
  | "TOKEN_QUOTA_EXCEEDED"
  | "DASHBOARD_PAGE_NOT_FOUND"
  | "CHART_DEFINITION_NOT_FOUND"
  | "PAGE_ACCESS_GRANT_NOT_FOUND"
  | "INVALID_ACCESS_GRANT_TARGET"
  | "ACCESS_GRANT_EMAIL_RATE_LIMIT"
  | "PAGE_ACCESS_TOKEN_INVALID"
  | "INVALID_CHART_DEFINITION"
  | "PROJECT_TEMPLATE_NOT_FOUND"
  | "INVALID_PROJECT_TEMPLATE_SKELETON"
  | "INVALID_PROJECT_TEMPLATE_CATEGORY"
  | "ACCOUNT_ALREADY_HAS_GOOGLE"
  | "INVALID_USER_NAME"
  | "TOO_MANY_PASSWORD_ATTEMPTS"
  | "REALTIME_TICKET_INVALID"
  | "SYNC_BATCH_TOO_LARGE"
  | "UNSUPPORTED_DERIVED_METRIC"
  | "INVALID_TASK_SCHEDULE"
  | "TASK_NOT_IN_TRASH"
  | "TASK_PARENT_IN_TRASH"
  | "INVALID_TASK_DEPENDENCY"
  | "TASK_DEPENDENCY_CYCLE"
  | "TASK_DEPENDENCY_NOT_FOUND"
  | "TASK_HAS_OPEN_BLOCKERS"
  | "WORKFLOW_STATUS_NOT_FOUND"
  | "INVALID_WORKFLOW_STATUS"
  | "LAST_STATUS_OF_CATEGORY"
  | "COMMENT_EDIT_NOT_ALLOWED"
  | "INVALID_COMMENT_REACTION"
  | "NOTIFICATION_NOT_FOUND"
  | "INVALID_SEARCH_QUERY"
  | "INVALID_TASK_RECURRENCE"
  | "TASK_RECURRENCE_NOT_FOUND"
  | "TASK_RECURRENCE_LIMIT_REACHED"
  | "TIME_ENTRY_NOT_FOUND"
  | "INVALID_TIME_ENTRY"
  | "NO_RUNNING_TIMER"
  | "SAVED_VIEW_NOT_FOUND"
  | "INVALID_SAVED_VIEW"
  | "INTAKE_FORM_NOT_FOUND"
  | "INVALID_INTAKE_FORM"
  | "INVALID_FORM_SUBMISSION"
  | "TASK_APPROVAL_NOT_FOUND"
  | "INVALID_TASK_APPROVAL"
  | "TASK_APPROVAL_CLOSED"
  | "INVALID_IMPORT_FILE"
  | "IMPORT_HAS_ERRORS"
  | "DATA_EXPORT_NOT_FOUND"
  | "DATA_EXPORT_NOT_READY"
  | "INVALID_TEMPLATE_INSTANTIATION"
  | "TEMPLATE_INSTANTIATION_NOT_FOUND"
  | "INVALID_TEMPLATE_MEDIA"
  | "INVALID_PROJECT_TEMPLATE_LISTING"
  | "TEMPLATE_AI_RATE_LIMIT_EXCEEDED"
  | "TEMPLATE_AI_GENERATION_FAILED"
  | "COUPON_NOT_FOUND"
  | "COUPON_CODE_ALREADY_EXISTS"
  | "INVALID_COUPON"
  | "COUPON_EXPIRED"
  | "COUPON_NOT_YET_VALID"
  | "COUPON_NOT_APPLICABLE_TO_PLAN"
  | "COUPON_REDEMPTION_LIMIT_REACHED"
  | "COUPON_ALREADY_REDEEMED"
  | "COUPON_HAS_REDEMPTIONS"
  | "ASSISTANT_CHANNEL_NOT_FOUND"
  | "ASSISTANT_CHANNEL_UNAVAILABLE"
  | "INVALID_CHANNEL_ADDRESS"
  | "ASSISTANT_CHANNEL_WORKSPACE_NOT_FOUND"
  | "TOO_MANY_CHANNEL_VERIFICATION_REQUESTS"
  | "CHANNEL_DELIVERY_FAILED"
  | "CHANNEL_VERIFICATION_NOT_FOUND"
  | "CHANNEL_VERIFICATION_INVALID_CODE"
  | "CHANNEL_VERIFICATION_MAX_ATTEMPTS_EXCEEDED"
  | "ASSISTANT_CHANNEL_LINK_NOT_FOUND"
  | "ASSISTANT_CHANNEL_CONVERSATION_NOT_FOUND"
  | "REQUEST_TIMEOUT"
  | "INTERNAL_ERROR";

export interface DomainErrorResponse {
  statusCode: number;
  code: ErrorCode;
  message: string;
  timestamp: string;
}

export interface ValidationErrorResponse {
  statusCode: number;
  message: string[] | string;
  error: string;
}

export type ApiErrorResponse = DomainErrorResponse | ValidationErrorResponse;

export type InvitationStatus = "PENDING" | "ACCEPTED" | "REVOKED" | "EXPIRED";

export const DEFAULT_PAGE_SIZE = 20;
export const MAX_PAGE_SIZE = 100;

export interface PaginationParams {
  page?: number;
  limit?: number;
}

export interface PaginationMeta {
  page: number;
  limit: number;
  total: number;
  totalPages: number;
}

export interface PaginatedResult<T> {
  data: T[];
  meta: PaginationMeta;
}

export function isDomainError(
  data: unknown
): data is DomainErrorResponse {
  return (
    typeof data === "object" &&
    data !== null &&
    "code" in data &&
    typeof (data as Record<string, unknown>).code === "string"
  );
}
